# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20170724_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='notes/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
